name = "Terminal"
license = "MIT"
licenselink = ""
description = "A dark terminal-aesthetic Hugo theme"
tags = ["dark", "terminal", "monospace", "minimal", "blog"]
min_version = "0.112.0"

[author]
  name = "Pablo Santos Luaces"
